packages:
  - packages/*
catalog:
  '@ant-design/icons-vue': ^6.1.0
  '@commitlint/cli': ^17.8.1
  '@commitlint/config-conventional': ^17.8.1
  '@panzoom/panzoom': ^4.6.0
  '@stan_bk/img-preload': '>=1.0.10'
  '@types/hammerjs': ^2.0.46
  '@types/lodash.clonedeep': ^4.5.9
  '@types/lodash.throttle': ^4.1.9
  '@typescript-eslint/eslint-plugin': ^5.62.0
  '@typescript-eslint/parser': ^5.62.0
  '@vitejs/plugin-vue': ^4.6.2
  '@vue/eslint-config-standard-with-typescript': ^8.0.0
  ant-design-vue: ^4.2.6
  chinese-chess-service: ^0.0.35
  commitizen: ^4.3.1
  cz-conventional-changelog: ^3.3.0
  eslint: ^8.57.1
  eslint-config-standard: ^17.1.0
  eslint-plugin-import: ^2.31.0
  eslint-plugin-n: ^15.7.0
  eslint-plugin-promise: ^6.6.0
  eslint-plugin-vue: ^9.3.0
  hammerjs: ^2.0.8
  husky: ^8.0.3
  lint-staged: ^13.3.0
  lodash: ^4.17.21
  lodash.clonedeep: ^4.5.0
  lodash.throttle: ^4.1.1
  sass: ^1.85.1
  socket.io-client: ^4.8.1
  typescript: ^4.9.5
  unit-path: ^0.0.4
  unplugin-auto-import: ^0.16.7
  unplugin-vue-components: ^0.25.2
  vconsole: ^3.15.1
  vite: ^4.5.9
  vitest: ^0.24.5
  vue: ^3.5.13
  vue-tsc: ^1.8.27
