packages:
  - packages/*
catalog:
  "@ant-design/icons-vue": ^6.1.0
  "@commitlint/cli": ^17.1.2
  "@commitlint/config-conventional": ^17.1.0
  "@panzoom/panzoom": ^4.6.0
  "@stan_bk/img-preload": ">=1.0.10"
  "@types/hammerjs": ^2.0.41
  '@types/lodash.clonedeep': ^4.5.9
  "@types/lodash.throttle": ^4.1.7
  "@typescript-eslint/eslint-plugin": ^5.41.0
  "@typescript-eslint/parser": ^5.41.0
  "@vue/eslint-config-standard-with-typescript": ^8.0.0
  "@vitejs/plugin-vue": ^4.5.2
  ant-design-vue: ^4.1.0
  chinese-chess-service: ^0.0.35
  commitizen: ^4.2.5
  cz-conventional-changelog: ^3.3.0
  eslint: ^8.22.0
  eslint-config-standard: ^17.0.0
  eslint-plugin-import: ^2.25.2
  eslint-plugin-n: ^15.0.0
  eslint-plugin-promise: ^6.0.0
  eslint-plugin-vue: ^9.3.0
  hammerjs: ^2.0.8
  husky: ^8.0.0
  lint-staged: ^13.0.3
  lodash: ^4.17.21
  lodash.clonedeep: ^4.5.0
  lodash.throttle: ^4.1.1
  sass: ^1.56.0
  socket.io-client: ^4.7.2
  typescript: ^4.6.4
  unit-path: ^0.0.4
  vconsole: ^3.15.1
  vitest: ^0.24.3
  vite: ^4.5.2
  vue-tsc: ^1.0.9
  vue: ^3.2.41
  unplugin-auto-import: ^0.16.7
  unplugin-vue-components: ^0.25.2
