extends:
  -  '../../.eslintrc.yml'
  - './.eslintrc-auto-import.json'
rules: {
  '@typescript-eslint/no-misused-promises': 0,
  '@typescript-eslint/restrict-plus-operands': 0,
  '@typescript-eslint/explicit-function-return-type': 0,
  '@typescript-eslint/promise-function-async': 0
}
