// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    CampSeat: typeof import('./src/components/ChessMain/CampSeat.vue')['default']
    ChatContainer: typeof import('./src/components/ChatContainer.vue')['default']
    ChessMain: typeof import('./src/components/ChessMain/index.vue')['default']
    ChessManual: typeof import('./src/components/ChessManual.vue')['default']
    GameController: typeof import('./src/components/ChessMain/GameController.vue')['default']
    IconSeat: typeof import('./src/components/IconSeat.vue')['default']
    LeftOutlined: typeof import('@ant-design/icons-vue')['LeftOutlined']
    Modal: typeof import('./src/components/Message/Modal.vue')['default']
    ModeSelector: typeof import('./src/components/ModeSelector.vue')['default']
    Spectator: typeof import('./src/components/ChessMain/Spectator.vue')['default']
    StatusWrapper: typeof import('./src/components/ChessMain/StatusWrapper.vue')['default']
  }
}
