/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    CampSeat: typeof import('./src/components/ChessMain/CampSeat.vue')['default']
    ChatContainer: typeof import('./src/components/ChatContainer.vue')['default']
    ChessMain: typeof import('./src/components/ChessMain/index.vue')['default']
    ChessManual: typeof import('./src/components/ChessManual.vue')['default']
    CloseOutlined: typeof import('@ant-design/icons-vue')['CloseOutlined']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    GameController: typeof import('./src/components/ChessMain/GameController.vue')['default']
    IconSeat: typeof import('./src/components/IconSeat.vue')['default']
    LeftOutlined: typeof import('@ant-design/icons-vue')['LeftOutlined']
    MessageOutlined: typeof import('@ant-design/icons-vue')['MessageOutlined']
    Modal: typeof import('./src/components/Message/Modal.vue')['default']
    ModeSelector: typeof import('./src/components/ModeSelector.vue')['default']
    ProfileOutlined: typeof import('@ant-design/icons-vue')['ProfileOutlined']
    SoundOutlined: typeof import('@ant-design/icons-vue')['SoundOutlined']
    Spectator: typeof import('./src/components/ChessMain/Spectator.vue')['default']
    StatusWrapper: typeof import('./src/components/ChessMain/StatusWrapper.vue')['default']
  }
}
