// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ClockCircleOutlined: typeof import('@ant-design/icons-vue')['ClockCircleOutlined']
    Enhancements: typeof import('./src/components/enhancements/index.vue')['default']
    Finished: typeof import('./src/components/modal/Finished.vue')['default']
    GameControl: typeof import('./src/components/header/GameControl.vue')['default']
    GameSetting: typeof import('./src/components/modal/GameSetting.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    LevelSetting: typeof import('./src/components/modal/LevelSetting.vue')['default']
    MineSweeper: typeof import('./src/components/MineSweeper.vue')['default']
    MinusOutlined: typeof import('@ant-design/icons-vue')['MinusOutlined']
    PlusOutlined: typeof import('@ant-design/icons-vue')['PlusOutlined']
    Statistics: typeof import('./src/components/modal/Statistics.vue')['default']
  }
}
