// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ArrowLeftOutlined: typeof import('@ant-design/icons-vue')['ArrowLeftOutlined']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    BarChartOutlined: typeof import('@ant-design/icons-vue')['BarChartOutlined']
    Bg: typeof import('./src/components/Bg.vue')['default']
    ClockCircleOutlined: typeof import('@ant-design/icons-vue')['ClockCircleOutlined']
    EllipsisOutlined: typeof import('@ant-design/icons-vue')['EllipsisOutlined']
    Enhancements: typeof import('./src/components/enhancements/index.vue')['default']
    Finished: typeof import('./src/components/modal/Finished.vue')['default']
    GameControl: typeof import('./src/components/header/GameControl.vue')['default']
    GameSetting: typeof import('./src/components/modal/GameSetting.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    MineSweeper: typeof import('./src/components/MineSweeper.vue')['default']
    MoreMenu: typeof import('./src/components/header/MoreMenu.vue')['default']
    PlayCircleFilled: typeof import('@ant-design/icons-vue')['PlayCircleFilled']
    SettingOutlined: typeof import('@ant-design/icons-vue')['SettingOutlined']
    Statistics: typeof import('./src/components/modal/Statistics.vue')['default']
  }
}
